# 服务名
spring:
  application:
    name: beacon-test
  # nacos地址
  cloud:
    nacos:
      discovery:
        #server-addr: 192.168.31.121:8848
        server-addr: 192.168.49.36:8848
  # datasource
  datasource:
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.49.36:3306/beacon_cloud?characterEncoding=utf-8&useSSL=false
    username: root
    password: 'xxiao0123'
# 端口号
server:
  port: 20000

# mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
